### ISSUE TITLE
In Clip_guided, auto_grad() error 

### ISSUE THREAD

**Issue by AlexMaOLS** [arpitbansal297/Universal-Guided-Diffusion#11]
Hi thank you for your sharing! I encounter an error related to the autograd() when I run the Clip_guided.py demo. Can you help me check with it? Thanks a lot!

Traceback (most recent call last):
  File "Guided/Clip_guided.py", line 160, in <module>
    output = operator.operator(label=None, operated_image=text)
  File "./Guided/helpers.py", line 255, in operator
    progress=self.progressive
  File "./guided_diffusion/gaussian_diffusion.py", line 958, in ddim_sample_loop_operation
    eta=eta,
  File "./guided_diffusion/gaussian_diffusion.py", line 1064, in ddim_sample_loop_progressive_operation
    eta=eta,
  **File "./guided_diffusion/gaussian_diffusion.py", line 684, in ddim_sample_operation
    grad = th.autograd.grad(selected.sum(), x_in)[0]**
  File "/home/ma-user/anaconda3/envs/PyTorch-1.10.2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.10.2/lib/python3.7/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "./guided_diffusion/nn.py", line 165, in backward
    allow_unused=True,
  File "/home/ma-user/anaconda3/envs/PyTorch-1.10.2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
**RuntimeError: One of the differentiated Tensors does not require grad**

**Comment by AlexMaOLS** [comment]
I found one solution, in Guided/helpers.py of get_model_diffusion_classifier(); comment the line 69: #model.requires_grad_(False) can make the code work. But the sampling time is too long, it takes 2 hours to create the samples in a V100 GPU.  Does it takes that long time for sampling?

**Comment by arpitbansal297** [comment]
Yes, it takes longer time due to 500 steps of diffusion and multiple self-recurrences.

**Comment by arnobanu** [comment]
> Yes, it takes longer time due to 500 steps of diffusion and multiple self-recurrences.

Hi. @arpitbansal297 
Is it okay to do that, or are there other ways?
Moreover, did you incorporate the diffusion model's gradient during backward guidance in your algorithm?
