### ISSUE TITLE
Throws a lot of errors after clean install

### ISSUE THREAD

**Issue by DenkingOfficial** [arpitbansal297/Universal-Guided-Diffusion#2]
It just doesn't work :(
I tried:
1. Create an env using commands provided in readme
2. Create an env manually
3. Run this on Ubuntu
4. Use various models

But it doesn't help

Logs:

```Traceback (most recent call last):
  File "C:\Software\Other Software\Universal-Guided-Diffusion\stable-diffusion-guided\face_detection.py", line 458, in <module>
    main()
  File "C:\Software\Other Software\Universal-Guided-Diffusion\stable-diffusion-guided\face_detection.py", line 419, in main
    for n, d in enumerate(dl, 0):
  File "C:\Software\Programming\Miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "C:\Software\Programming\Miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Software\Programming\Miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
    w.start()
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'
(ldm) PS C:\Software\Other Software\Universal-Guided-Diffusion\stable-diffusion-guided> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Software\Programming\Miniconda\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

PC Specs:
OS: Windows 10 (21H2) / Ubuntu 20.04 (WSL)
CPU: Intel Core i5 9400F
GPU: RTX 2060 Super (8GB VRAM)
RAM: 16 GB

**Comment by DenkingOfficial** [comment]
I guess my GPU just can't handle it :(
I set num_workers to 0 in segmentation. py (line 423) and now it seems to work, but I get OOM error

**Comment by pengzhangzhi** [comment]
Hi. Just so you know, I ran the face example, which takes 16G GPU Memory.

**Comment by ninjasaid2k** [comment]
> Hi. Just so you know, I ran the face example, which takes 16G GPU Memory.

is there a way to optimize it? That's basically worse than Dreambooth.
